### ISSUE TITLE
Ensure every bot invites neurobot to the room if it's not present

### ISSUE THREAD

**Issue by psrpinto** [Automattic/neurobot#104]
It should not be possible to have, for example, `@afkbot` in a room in which `@neurobot` is not present.

**Comment by ashfame** [comment]
@psrpinto I forgot our reasoning behind this decision. I was thinking we need non-primary bots to run sync to be able to respond to invitations anyway, so do we really need neurobot to listen to reactions for other bots if they are also listening?
