### ISSUE TITLE
Proposal: HTTP API

### ISSUE THREAD

**Issue by psrpinto** [Automattic/neurobot#28]
Currently, what `/webhook-listener` does is to create a trigger, so I'd like to propose to make that explicit in the endpoint name, by naming it something like `/trigger`, `/trigger/create`, `/create-trigger`, etc. Alternatively, we could make it REST-ish and just call it `/trigger` and use HTTP verbs for the action, e.g. `POST /trigger` would create a new trigger.

Additionally, at the moment, `/webhook-listener` is the only endpoint, but we could envision having other endpoints in the future. So I would also propose to namespace these endpoints under e.g. `/api`. So the endpoint URL would become `/api/trigger`, for example.

This would facilitate having reverse proxies forward all `/api` requests to neurobot, in the event where there would be, for example, an admin UI available under `/`.

**Comment by ashfame** [comment]
Thanks for bringing this up! Let's figure it out.

`/webhook-listener` doesn't actually create a trigger. It only allows a type of trigger (`webhook` trigger) to be triggered.
REST-y approach doesn't fit the semantics at all, IMO.
Something like `/catch-trigger` sounds better, but then again not a tight semantic fit.

Good idea on namespacing, how about `/api/v1/ping`? That way `trigger` resource can be REST-y or whatever in future.

**Comment by ashfame** [comment]
Yeah `/webhook-trigger` works but should we try to do `/api/v1/webhook-trigger` now?
