### ISSUE TITLE
Matrix command support

### ISSUE THREAD

**Issue by ashfame** [Automattic/neurobot#69]
- [ ] Neurobot tracks unique events only
- [ ] Neurobot check every message across every room and log it to Stdout 
- [ ] Neurobot recognises presence of a command in a message
- [ ] Neurobot extracts payload out of the arguments supplied and responds if required args are missing
- [ ] Neurobot invokes the workflow

**Comment by psrpinto** [comment]
Closing since split into multiple issues.
