### ISSUE TITLE
Homeservers on non-standard ports (localhost:8008)

### ISSUE THREAD

**Issue by psrpinto** [Automattic/neurobot#86]
I'm confused about what to set the `MATRIX_SERVER_NAME` environment variable to when the server is running on a non-standard port, which is the case when running locally with matrix-env (localhost:8008).

The variable is called SERVER_NAME but I'm passing a server URL, which makes me think something is off.

I think there will also be an issue with automatically joining a room when the bot is invited since that checks if the homeserver domain is the same, but when using matrix-env the homeserver domain is `matrix.test`, but the URL is localhost:8008.

**Comment by ashfame** [comment]
Don't we already required it? I already have it in my hosts file.

But yeah, serving .well-known definitely would require pointing it to local machine. We can also use a subdomain of an actual domain and point it to 127.0.0.1 to just use it for local stuff though.

**Comment by psrpinto** [comment]
I was under the impression adding to `/etc/hosts` was not required, but I just confirmed I also have it in there, so please ignore my comment.

**Comment by ashfame** [comment]
No worries. Would you say your concern has been addressed or would you like to pursue some change in variable name in `.env`? We should create an issue for .well-known for matrix.test on the right repo?

**Comment by psrpinto** [comment]
When dealing with [this remark](https://github.com/Automattic/neurobot/pull/118#pullrequestreview-941329458), something feels off about the `MATRIX_SERVER_NAME` variable.

The variable is called `MATRIX_SERVER_NAME`, but it also takes the port, for example `matrix.test:443` (as per `.env.sample`), or `matrix.test:8080`. So I think a more appropriate name could be `MATRIX_SERVER_HOST`.

However, maybe it would be better to instead make it a URL and call it `MATRIX_SERVER_URL`?

```
MATRIX_SERVER_URL=https://matrix.test
MATRIX_SERVER_URL=http://matrix.test:8080
```

**Comment by ashfame** [comment]
I wouldn't want to break convention for accommodating that. I tried explaining [above](https://github.com/Automattic/neurobot/issues/86#issuecomment-1091360419) why only unusual setups would need to provide a port in there, for a good reason too. Majority of the setups wouldn't have to.

`MATRIX_SERVER_URL` is what we discover for a particular `Matrix server name`, which I think came from `Matrix server domain name`, that's used for namespacing addresses. So using that would be semantically incorrect IMO.

And if we try to give it a different name, then I arrive at the question of why think for an another term for it, when it's described by `Matrix server name` in Matrix ecosystem already?

**Comment by psrpinto** [comment]
Ok, so should we remove the port from `env.sample`?

**Comment by psrpinto** [comment]
Nevermind, lets just close this.
